apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
---
apiVersion: v1
kind: Service
metadata:
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
spec:
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: clusterpedia-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterpedia-apiserver
  namespace: clusterpedia-system
  labels:
    app: clusterpedia-apiserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clusterpedia-apiserver
  template:
    metadata:
      labels:
        app: clusterpedia-apiserver
    spec:
      containers:
      - name: apiserver
        image: ghcr.io/clusterpedia-io/clusterpedia/apiserver:v0.7.0
        command:
        - /usr/local/bin/apiserver
        - --secure-port=6443
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - -v=3
        - --middleware-name=rabbitmq
        - --middleware-serverIp=rabbitmq-cluster.rabbitmq-system.svc
        - --middleware-user=$(RABBITMQ_USER)
        - --middleware-serverPort=5672
        - --middleware-password=$(RABBITMQ_PASSWD)
        - --cache-size=200
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: internalstorage-password
              key: password
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-connect
              key: user
        - name: RABBITMQ_PASSWD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-connect
              key: password
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
      serviceAccountName: clusterpedia-apiserver
      volumes:
      - name: internalstorage-config
        configMap:
          name: clusterpedia-internalstorage
