apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterpedia-clustersynchro-manager
  namespace: clusterpedia-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterpedia-clustersynchro-manager
  namespace: clusterpedia-system
  labels:
    app: clusterpedia-clustersynchro-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clusterpedia-clustersynchro-manager
  template:
    metadata:
      labels:
        app: clusterpedia-clustersynchro-manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/clusterpedia-io/clusterpedia/clustersynchro-manager:v0.7.0
        command:
        - /usr/local/bin/clustersynchro-manager
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        - --feature-gates=PruneManagedFields=true,PruneLastAppliedConfiguration=true
        - --kubeconfig=/etc/clusterpedia/manager-kubeconfig
        - --middleware-name=rabbitmq
        - --middleware-serverIp=rabbitmq-cluster.rabbitmq-system.svc
        - --middleware-user=$(RABBITMQ_USER)
        - --middleware-serverPort=5672
        - --middleware-password=$(RABBITMQ_PASSWD)
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: internalstorage-password
              key: password
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-connect
              key: user
        - name: RABBITMQ_PASSWD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-connect
              key: password
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
        - name: manager-kubeconfig
          mountPath: /etc/clusterpedia/
          readOnly: true
      serviceAccountName: clusterpedia-clustersynchro-manager
      volumes:
      - name: internalstorage-config
        configMap:
          name: clusterpedia-internalstorage
      - name: manager-kubeconfig
        configMap:
          name: clustersynchro-manager-kubeconfig